version: "3.9"  # optional since v1.27.0
services:
  cart:
    container_name: cart
    image: dheerajdevops123/cart:150
    environment:
      REDIS_HOST: redis
      CATALOG_HOST: catalogue
    depends_on:
      - catalogue
      - redis
  catalogue:
    container_name: catalogue
    image: dheerajdevops123/catalogue:151
    environment:
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    image: dheerajdevops123/frontend:169
    ports:
        - "80:80"
    depends_on:
      - catalogue
      - shipping
  mongodb:
    container_name: mongodb
    image: dheerajdevops123/mongodb:153
  redis:
    container_name: redis
    image: redis
  mysql:
    container_name: mysql
    image: dheerajdevops123/mysql:174
    environment:
      MYSQL_ROOT_HOST: "root"
      MYSQL_ROOT_PASSWORD: "password"
  user:
    container_name: user
    image: dheerajdevops123/user:158
    environment:
      MONGO_URL: "mongodb://mongodb:27017/users"
      REDIS_HOST: "redis"
    depends_on:
      - mongodb
      - redis
  shipping:
    container_name: shipping
    image: dheerajdevops123/shipping:170
    environment:
      CART_ENDPOINT: "cart:8080"
      DB_HOST: "mysql"
    depends_on:
      - cart
      - mysql



