version: "3.9"  # optional since v1.27.0
services:
  cart:
    image: dheerajdevops123/cart:150
  catalogue:
    image: dheerajdevops123/catalogue:151
  frontend:
      image: dheerajdevops123/frontend:152
