version: "3.9"  # optional since v1.27.0
services:
  cart:
    image: dheerajdevops123/cart:150
  catalogue:
    image: dheerajdevops123/catalogue:151
    environment:
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
  frontend:
      image: dheerajdevops123/frontend:152
      ports:
        - "80:80"
  mongodb:
    image: dheerajdevops123/mongodb:153
    container_name: mongodb
