version: "3.9"  # optional since v1.27.0
services:
  cart:
    container_name: cart
    image: dheerajdevops123/cart:150
  catalogue:
    container_name: catalogue
    image: dheerajdevops123/catalogue:151
    environment:
      MONGO_URL: "mongodb://mongodb:27017/catalogue"
    depends_on:
      - mongodb
  frontend:
    container_name: frontend
    image: dheerajdevops123/frontend:156
    ports:
        - "80:80"
    depends_on:
      - catalogue
  mongodb:
    container_name: mongodb
    image: dheerajdevops123/mongodb:153

